[package]
name = "pgn_reader"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
crossterm = "0.29.0"
indicatif = "0.18.4"
ratatui = "0.30.0"
rusqlite = { version = "0.38.0", features = ["bundled"] }
ureq = "3.2.0"
zstd = "0.13.3"
